### ISSUE TITLE
I have a question about ROCm-Doc Instruction Set Architecture

### ISSUE THREAD

**Issue by briansp2020** [ROCm/ROCm-ComputeABI-Doc#1]
From https://github.com/RadeonOpenCompute/ROCm-Docs/blob/master/AMDGPU-ABI.md#instruction-set-architecture, I see that Tonga & ROCm Tonga are different stepping and Fiji & ROCm Fiji are different steppings. Where can I find out about the differences?
Purely speculating based on that table,  I'd guess that Tonga was updated with PCIe Gen3 atomic and is used in ROCm platform. However, that does not quite make sense for Fiji since ROCm Fiji with PCIe Gen3 atomic is listed as a lower stepping than Fiji.
Where can I find out more information?

**Comment by nhaustov** [comment]
Yes, ROCm Tonga differs from Tonga by PCIe Gen3 system scope atomics. The reason stepping seems to be out-of-order is purely historical and has no special significance.

**Comment by briansp2020** [comment]
@nhaustov 
Does that mean that some early Fiji based board available on the market will not work properly with ROCm? Or, is it just pre-release hardware that does not support PCIe Gen3 system atomics?

Thanks for you reply.

**Comment by nhaustov** [comment]
From my understanding, it is bridge and not GPU board that matters. So Fiji (any) + Haswell may be required to get ROCm Fiji. See https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/master/README.md
Maybe someone who is more familiar with hardware can also jump in.

**Comment by jedwards-AMD** [comment]
Any Fiji should be detected and work as long as the CPU is a Haswell.

**Comment by briansp2020** [comment]
Does that mean Kaveri + Fiji will not work using ROCm-1.1.1? If it won't work, it that hardware limitation or software limitation?

**Comment by aditya4d** [comment]
Its hardware limitation. Kaveri is PCIe 2.0.

**Comment by briansp2020** [comment]
Ok. Thank you.
Time for me to start shopping for a new MB & CPU. I wish AM4 platform is released soon.

**Comment by briansp2020** [comment]
According to [this page](http://products.amd.com/en-us/search/APU/AMD-A-Series-Processors/AMD-A10-Series-APU-for-Desktops/A10-7850K-with-Radeon%E2%84%A2-R7-Series/10), Kaveri has PCIe 3.0. Maybe Kaveri does not support platform atomic because it is an optional feature of 3.0 spec?

**Comment by aditya4d** [comment]
Well, it doesnt supoport what needed for ROCm

**Comment by gstoner** [comment]
The current release with Fiji Generation GPU need PCIe Platform Atomics and currently, only Haswell or new CPU have this capability.  Why we need PCIe Atomics is to support HSA  Signals. Here is link to the API http://bit.ly/1S0are6.  We leverage CAS, FetchADD, SWAP. 

Here is document on PCIe Atomics https://pcisig.com/sites/default/files/specification_documents/ECN_Atomic_Ops_080417.pdf

**Comment by briansp2020** [comment]
Thank you for the answers. @nhaustov  @jedwards-AMD  @adityaatluri  @gstoner

**Comment by briansp2020** [comment]
@gstoner
Some more questions. When can we expect to use AMD processor for ROCm platform? I tried ROCm on Kaveri+Fiji and, as expected, it did not work. So, I'm reluctantly upgrading my CPU with Intel stuff. When Zen comes out, I suppose ROCm will work with it? How about Bristol/Stoney Ridge?

Also, I thought Fiji had some special hardware capability that was required by ROCm. Is there any capability differences between ROCm+Fiji and ROCm+Hawaii?

Also, according to RX 480 review, they mention native float 16 capability (http://www.tomshardware.com/reviews/amd-radeon-rx-480-polaris-10,4616.html). What does native float 16 capability mean? Does it mean that float 16 performance will be 2 times higher, in terms of flop, than float 32? Will that capability be exposed in the [next ROCm release](https://twitter.com/angstroms/status/748291183042920449)?

Thanks!

**Comment by gstoner** [comment]
Tonga, Fiji and Polaris all support Float16 Instructions,  they are 1x rate so the same as Singles in this generation of GPU.

Carizzo does not support PCIe  Gen 3 Platform Atomics which is why Fiji does not work.    For Hawaii class GPU and only Hawaii class GPU we will relax the PCIe Atomic capability since the GFX7 GPU family did not support Atomics.  This bring older process to be supported by ROCm for this Family of hardware.

On the question of CPU’s, It will be AMD Xen based CPU’s  when we have PCIe Gen 3  Platform Atomics.

Greg

On Jun 30, 2016, at 10:42 AM, Brian <notifications@github.com<mailto:notifications@github.com>> wrote:

@gstonerhttps://github.com/gstoner
Some more questions. When can we expect to use AMD processor for ROCm platform? I tried ROCm on Kaveri+Fiji and, as expected, it did not work. So, I'm reluctantly upgrading my CPU with Intel stuff. When Zen comes out, I suppose ROCm will work with it? How about Bristol/Stoney Ridge?

Also, I thought Fiji had some special hardware capability that was required by ROCm. Is there any capability differences between ROCm+Fiji and ROCm+Hawaii?

Also, according to RX 480 review, they mention native float 16 capability (http://www.tomshardware.com/reviews/amd-radeon-rx-480-polaris-10,4616.html). What does native float 16 capability mean? Does it mean that float 16 performance will be 2 times higher, in terms of flop, than float 32? Will that capability be exposed in the next ROCm releasehttps://twitter.com/angstroms/status/748291183042920449?

Thanks!

**Comment by briansp2020** [comment]
@gstoner 
Does that mean it may be possible to get ROCm running on Kaveri + Hawaii? Or hack the kernel and get Kaveri + Fiji working by using the queuing method used for Hawaii? 

That possibility intrigues me. :)

Thank you for your answer!

**Comment by aditya4d** [comment]
Hi @briansp2020 ,
Here what it is,
[GFX7](http://developer.amd.com/wordpress/media/2012/12/AMD_Southern_Islands_Instruction_Set_Architecture.pdf): Can work with Kaveri, Carrizo and newer. No fp16. 
[GFX8](http://amd-dev.wpengine.netdna-cdn.com/wordpress/media/2013/07/AMD_GCN3_Instruction_Set_Architecture.pdf): Can work with any CPU with PCIe + atomics. Native fp16 support.

Changing KFD isn't really productive to make atomics work.

I recommend bookmarking the docs. They are the ones which drive the whole HIP and HCC support. First place to visit in doubt.

**Comment by gstoner** [comment]
Kaveri and Hawaii could be possible we have not tested it.     Hacking Kaveri + FIJI is not recommended.  This complex set of software runtime, driver, thunk, kernel driver, and microcode they have to all work together.   If you break this then the tools do not work for Fiji. We will not support it.

On Jun 30, 2016, at 12:59 PM, Brian <notifications@github.com<mailto:notifications@github.com>> wrote:

@gstonerhttps://github.com/gstoner
Does that mean it may be possible to get ROCm running on Kaveri + Hawaii? Or hack the kernel and get Kaveri + Fiji working by using the queuing method used for Hawaii?

That possibility intrigues me. :)

Thank you for your answer!

**Comment by briansp2020** [comment]
@gstoner 
Thanks for the reply. That's the beauty of open source. If the vendor will not support it, I can just roll my own solution. :)
:+1:

**Comment by zdnz** [comment]
#1  PCI 3.0 the main requirement for ROCm or does the processor generation matter?  I know I've seen Xeon V2 motherboards with PCI 3.0.  Technically these PCI 3.0 motherboards supported Xeon V2 or V3.  Would these PCI 3.0 motherboards work for RCOm with Xeon V2 processors?  I think I may have even seen Xeon V1 with PCI 3.0.  Is there anything specific to the processor generation or is it just the PCI 3.0 that is required for full ROCm support?

**Comment by briansp2020** [comment]
You need PCIe 3.0 that supports system atomic. 
See https://radeonopencompute.github.io/hardware.html 

> CPU support: ROCm requires CPUs with PCIe Gen3 atomics capability, such as the Intel Xeon E5v3 and newer Xeon processors. It also supports consumer CPUs, such as Haswell-class Intel Core CPUs (v3 and newer). We know you’re going to ask—yes, ROCm is optimized to pull all the rich capabilities out of the new AMD Zen-based processors.
