### ISSUE TITLE
Right columnsa of wide tables are clipped

### ISSUE THREAD

**Issue by jamborm** [ROCm/ROCm-ComputeABI-Doc#5]
In the github rendering of this markdown file, at least when displayed
both in a recent Firefox and a Chromium browser, the wide tables have
their right column clipped to the point when it is unreadable and one
has to read the information from the source.  For example, look at the
rendering of table titled "AMD Kernel Code Object amd_kernel_code_t"

Admittedly, this is perhaps more of a github bug than a bug of this
document but I do not know where to file those and wanted to make you
aware of the issue nevertheless.

**Comment by nhaustov** [comment]
For me, in Google Chrome, the table has a scrollbar at the bottom. Any hint what can be done to make it look better?

**Comment by jamborm** [comment]
Ah, indeed, the bars are so thin I did not notice them.  So I suppose the issue is that the document cannot be easily printed or converted to a PDF for later reading offline.  

However, that seems to be a Github rendering issue rather than anything else, so I will not feel bad if you just close this. If I ever have a free moment, I'll try to search for some other reasonable markdown renderer.
