### ISSUE TITLE
amd_compute_pgm_rsrc2_t inconsistent names

### ISSUE THREAD

**Issue by almson** [ROCm/ROCm-ComputeABI-Doc#6]
Fields such as `enable_sgpr_workgroup_id_x` and `enable_sgpr_workgroup_info` have different names in the LLVM assembler. (`compute_pgm_rsrc2_tgid_x_en` and `compute_pgm_rsrc2_tg_size_en` respectively.) Please make the ABI doc and the assembler consistent with eachother.

**Comment by nhaustov** [comment]
LLVM assembler needs to be updated to use names defined in ABI doc.

**Comment by gstoner** [comment]
Thank you for reporting this.   We recently made changes to this document on the direction we are going to  set compute capability not using codenames. The team is in the process of updating the assembler to support this capability as specified.    Here the Documentation is leading implementation of functionality, it not self-consistancy issue as you have report it.

On Aug 28, 2016, at 9:28 AM, Nikolay Haustov <notifications@github.com<mailto:notifications@github.com>> wrote:

LLVM assembler needs to be updated to use names defined in ABI doc.

**Comment by vpykhtin** [comment]
The change has been submitted by Sam Kolton to the llvm trunk: https://reviews.llvm.org/D24296
