### ISSUE TITLE
How to get work-group/thread-group/tile size?

### ISSUE THREAD

**Issue by almson** [ROCm/ROCm-ComputeABI-Doc#7]
I see that `enable_sgpr_workgroup_info` records some sort of flat work group size, but I don't see anywhere how to get a per-dimension size.

**Comment by nhaustov** [comment]
Workgroup sizes are available in AQL dispatch packet which is defined in HSA SysArch specifcation (linked from the doc). The address of dispatch packet may be obtained through Dispatch Ptr sgpr (enable_sgpr_dispatch_ptr).
